# Generated by Django 4.0.3 on 2022-03-20 01:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='name',
            new_name='room_name',
        ),
        migrations.CreateModel(
            name='User_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='rooms.rooms')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rooms.users')),
            ],
        ),
    ]
