# Generated by Django 4.0.3 on 2022-03-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='where',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rooms.room'),
        ),
    ]
