# Generated by Django 4.0.3 on 2022-03-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
